field.formatter.settings.baguettebox:
  type: mapping
  label: Formatter settings
  mapping:
    image_style:
      type: string
      label: Image style
    baguette_image_style:
      type: string
      label: Image style
    baguette_image_style_responsive:
      type: sequence
      label: Baguettebox image style (responsive)
      sequence:
        type: mapping
        mapping:
          width:
            type: integer
            label: Width
          image_style:
            type: string
            label: Image style
    animation:
      type: string
      label: Animation
    captions_source:
      type: string
      label: Captions source
    buttons:
      type: boolean
      label: Display buttons
    fullscreen:
      type: boolean
      label: Enable full screen mode
    hide_scrollbars:
      type: boolean
      label: Hide scrollbars when gallery is displayed
    inline:
      type: boolean
      label: Display as inline elements
